### ISSUE TITLE
Make a copy of a spreadsheet and rename spreadsheet

### ISSUE THREAD

**Issue by g4spow** [nithinmurali/pygsheets#169]
I need to make a complete copy of a spreadsheet(not worksheet) and also rename it to it's ID.
ie. Like you would do using "File-Make a Cop" and also rename "stockdata" to "12xxlLWhrhnTMP7yDxVLaA_amWdhTFIFazyo9N7gG9_I"

Is this possible in pygsheets?

**Comment by nithinmurali** [comment]
you can't copy a spreadsheet using pygsheets, you will have to use the drive api for that. Though you can use the drive_service object in pyghseets client. As for renaming its as simple as `ss.title= ss.id`

Please use stack-overflow for usage related question with pyghseets tag

**Comment by tehfink** [comment]
It would be nice if the method `create(self, title, parent_id=None)` took a `template` parameter, which would basically just copy an existing document. What do you think?

**Comment by nithinmurali** [comment]
That could be useful.

**Comment by mateolan** [comment]
+1 For copying a template spreadsheet into a new spreadsheet.

**Comment by tehfink** [comment]
@nithinmurali Thanks!

**Comment by ashwinramdas12** [comment]
I have tried the create function and specified a spefici spreadsheet for the template, but it creates a completely blank spreadsheet instead of making a copy of the template.

**Comment by EricPreventa** [comment]
> @nithinmurali I have tried the create function and specified a spefici spreadsheet for the template, but it creates a completely blank spreadsheet instead of making a copy of the template.

I'm also having this problem now. I thought I got it to work earlier, so not sure what happened or where the bug may be.

**Comment by nithinmurali** [comment]
fixed this

**Comment by ashwinramdas12** [comment]
@nithinmurali Still does not work for me. Do I need to update pysheets?

**Comment by nithinmurali** [comment]
@ashwinramdas12 Is it not released and is still in staging. you can install it via

`pip install https://github.com/nithinmurali/pygsheets/archive/master.zip
`

**Comment by ashwinramdas12** [comment]
@nithinmurali Just tried it with the new install. Still getting a blank sheet instead of a copy of the template.

**Comment by nithinmurali** [comment]
thats strange. i just tested it and is working fine. Are you sure you are installing from staging branch. did you remove your old version before installing?

**Comment by ashwinramdas12** [comment]
I copied and pasted the pip install line you sent. It says I now have version 2.0.3 installed. I'll try uninstalling and reinstalling with what you sent and then try again

**Comment by ashwinramdas12** [comment]
![image](https://user-images.githubusercontent.com/63090417/80939331-93f45f00-8d99-11ea-90c1-da64d72897e6.png)

For reference, the above is what I'm testing for the template. Don't know if that affects anything, but just making sure

**Comment by ashwinramdas12** [comment]
@nithinmurali Still blank upon uninstall, reinstall and retry.

**Comment by nithinmurali** [comment]
@ashwinramdas12 the data in the sheet shouldn't matter, its copying the whole file. i just tested installing from scratch and its working fine. somehow you are not getting the latest version. maybe the pip is using old cache

``
pip install --no-cache-dir https://github.com/nithinmurali/pygsheets/archive/staging.zip
``
check the install logs to see if its actually installing.

if these also dosen't work your only option is to clone and install from source.

**Comment by ashwinramdas12** [comment]
Okay I think I must have the latest now. Now it is throwing an error instead of making a new sheet, but that at least must mean I have finally updated it. Here is the error:

![image](https://user-images.githubusercontent.com/63090417/80941512-df117080-8d9f-11ea-8867-a305e17c0d51.png)

**Comment by nithinmurali** [comment]
okay. Again i couldn't reproduce it. Is this the complete stacktrace? I cant see the key 'parents' used anywhere.

**Comment by ashwinramdas12** [comment]
@nithinmurali When I created a new jupyter notebook and ran my code it worked! Thank you so much for your help.

**Comment by cuchoi** [comment]
Hi @ashwinramdas12, do we still need to install from staging to be able to use the template?

**Comment by cuchoi** [comment]
It seems that it is still needed, are there any plans for a new release that will include this? 

Thanks for building this great library!

**Comment by Tomzer42** [comment]
Hello everybody,

I also need to create a spreadsheet from a template and as everybody I only got a blank sheet with the correct sheet name.
Does anyone know if a release is planned to fix this bug?

Thanks to other features I successed in copy/pasting the values and the format of the template but it's much longer...

Have a great week,
Tom

**Comment by nithinmurali** [comment]
@Tomzer42  a new version is released. https://github.com/nithinmurali/pygsheets/releases/tag/2.0.4

**Comment by Tomzer42** [comment]
Thank you very much !!!!!

It's working now :)

Thanks again for this very useful package.

Have a nice day,
Tom
