### ISSUE TITLE
duplicate gsheet at home and specified folder

### ISSUE THREAD

**Issue by ellenpramana** [nithinmurali/pygsheets#297]
When I try to create a gsheet on specific folder, it create double files. One in the give specific folder (based on the specified parent id), the other at the home drive. Is there a way to create only 1 in the specific folder? 

import pygsheets
gc = pygsheets.authorize(outh_file=CLIENT_SECRETS)
sheet = gc.create('try', parent_id = 'xxx')

Thank you.

**Comment by nithinmurali** [comment]
I think think this was an old big which was fixed. What is your pygsheets version, form where did you install it?

**Comment by ellenpramana** [comment]
Yeah I also was looking at the previous issue and checked the commit as
well.
However, I am confused that I still get the same error.
My pygsheet version is 1.1.4. I think this is the newest version, right?
I installed it using pip.
Thank you.

Ellen

**Comment by nithinmurali** [comment]
This is fixed in the trunk after the 1.1.4 release. So fix should be out with 2.0. meanwhile you can install pygsheets from github to get the fix.

**Comment by nithinmurali** [comment]
bah, probably wont be releasing a 1.1.5.
